name: Check for updates

on:
  schedule:
    # Runs every 6 hours
    - cron: '52 3/6 * * *'
  workflow_dispatch: 

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Flatpak External Data Checker
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: imngkhang
          GIT_COMMITTER_NAME: imngkhang
          GIT_AUTHOR_EMAIL: nnguyenkhang14@gmail.com
          GIT_COMMITTER_EMAIL: nnguyenkhang14@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # --never-fork is needed because the repository permissions
          # reported by the GitHub API claim that the user cannot push to the
          # repo, whereas in fact they can.
          args: |
            --verbose --update --never-fork cn.eeo.ClassIn.json